Nastya/forms
tomasnyvlt/4IT580 pull request #1
Opened 2022-10-24 13:37 UTC by AnastasiiaZlatieva

Forms for sign- in and register page

2022-10-25 09:09 UTC, mkapal commented on apps/fe/components/forms/Register.tsx
> +
teest

2022-10-25 09:51 UTC, tomasnyvlt requested changes

2022-10-26 11:49 UTC, tomasnyvlt requested changes

2022-10-26 11:49 UTC, tomasnyvlt commented on apps/fe/components/forms/Register.tsx
> +          <InputField name="emailConfirmation" label="Podtvrdi email" placeholder="napis email znovu" />
Email confirmation taky přidat email

2022-10-26 11:49 UTC, tomasnyvlt commented on apps/fe/shared/hook-form/FormField.tsx
> +function InputField({ name, label, placeholder, type, children, Component = Input, ...props }: InputName) {
šlo by pls taky udělat FC?
`const InputField: FC<InputName> = ({ name, label, placeholder, type, children, Component = Input, ...props }) => { `

2022-10-26 11:49 UTC, tomasnyvlt commented on apps/fe/shared/hook-form/FormField.tsx
> +      <FormErrorMessage>{error}</FormErrorMessage>
Nevím, jestli FormErrorMessage nemá nějaký styly, asi by bylo lepší udělat ještě {error && <FormErrorMessage ....

2022-10-26 11:49 UTC, tomasnyvlt commented on apps/fe/components/forms/Register.tsx
> +      month: "mesic"
tady je initialValue pro month, ale chybí day a year a pak "mesic" asi nebude initialValue pro month

2022-10-26 12:25 UTC, AnastasiiaZlatieva commented on apps/fe/shared/hook-form/FormField.tsx
> +      <FormErrorMessage>{error}</FormErrorMessage>
tady nerozumim😕
to ma defaultne styl ze to pise cervenym, chceme nejak jinak?

2022-10-27 07:32 UTC, merged